services:
  - name: annatar
    env:
      - key: LOG_LEVEL
        value: "debug"
      - key: JACKETT_URL
        value: "http://45.154.87.104:9117"
      - key: JACKETT_API_KEY
        value: "6ebybwn3luj2nwyx4063naqjx82hvwuj"
      - key: JACKETT_MAX_RESULTS
        value: "10"
      - key: JACKETT_TIMEOUT
        value: "5"
      - key: JACKETT_INDEXERS
        value: "backups,bigfangroup,bitsearch,btsow,extremlymtorrents,knaben,leech24,movieworld,sktorrent-org,solidtorrents,therarbg,torlock,torrentdownloads,torrentfunk,torrentleech,torrentseeds-api,torrentz2nz,xtremebytes,yourbittorrent"
      - key: LISTEN_PORT
        value: "8000"

    buildCommand: |
      docker build -t registry.gitlab.com/helpyourself/annat-update:latest .

    startCommand: "python run.py"

    healthCheckPath: "/"

    volumes:
      - "redis_data:/app/data"

    ports:
      - "8000:8000"

    dependsOn:
      - jackett

  - name: jackett
    image: docker.io/linuxserver/jackett
    env:
      - key: PUID
        value: "1000"
      - key: PGID
        value: "1000"

    ports:
      - "9117:9117"

    volumes:
      - jackett_config:/config
